# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  
  # Image Chosen
  config.vm.box = "box-cutter/ubuntu1404-desktop"

  
  

  
   config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true
     vb.name = "Resolve"
  
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
   end
  

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. 

   config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
	 #install JDK
     sudo apt-get install -y openjdk-7-jre
     sudo apt-get install -y openjdk-7-jdk
	 cd /home/vagrant/Desktop/
	 #Downloading the relevant files from Drive
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/Installation.txt
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/mozilla_license.txt
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/Readme.txt
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/Resolve_License.txt
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/startup.sh
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/YouTubeDemo.desktop
	 wget https://googledrive.com/host/0ByN4zmGGN7D6ZWUyanBQSzlRdTg/Resolve.zip
	 unzip Resolve.zip
	 #installing SQL 
	 sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password password'
	 sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password password'
	 sudo apt-get install -y mysql-server-5.5
	 sleep 5
	 
	 #installation steps for the tool
	 printf '%s\n' 'CREATE DATABASE resolvedb;'>query
	 sleep 1
	 mysql -u root -ppassword < /home/vagrant/Desktop/query
	 mysql -u root -ppassword resolvedb < /home/vagrant/Desktop/RESOLVE_DB.sql
	 cd /home/vagrant/Desktop/RESOLVEWebIDE-v4
	 #starting the tool
	 /home/vagrant/Desktop/play-1.2.5.5/play deps
	 /home/vagrant/Desktop/play-1.2.5.5/play run
	 sleep 20
	 firefox&
	 sudo mkdir /home/vagrant/.config/autostart
	 sudo cp /home/vagrant/Desktop/startup.sh /home/vagrant/.config/autostart/

   SHELL
end
